<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>name</key>
	<string>MSX Basic classic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msx-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.function.msx-basic-classic</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>comment.msx-basic-classic</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((start|^end|^lines|^size))|((^[0-9a-fA-F]{4})(:)([ 0-9a-fA-F]{5}(?:[ 0-9a-fA-F]{5})?)([ 0-9a-fA-F]{3})+)?(\s{8}|$)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=data)</string>
					<key>end</key>
					<string>(?=:)|$</string>
					<key>name</key>
					<string>constant.global.msx-basic-classic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>"</string>
							<key>end</key>
							<string>"|$</string>
							<key>name</key>
							<string>constant.global.msx-basic-classic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"|$</string>
					<key>name</key>
					<string>string.quoted.double.msx-basic-classic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.msx-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msx-basic-classic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>comment.msx-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)((')|(rem))(.*)$</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:error|interval|key|sprite|stop|strig)\s*(?=(?i:goto|gosub))</string>
					<key>name</key>
					<string>support.function.msx-basic-classic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:asc)</string>
					<key>name</key>
					<string>support.function.msx-basic-classic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.msx-basic-classic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.msx-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i:(fn)\s*(\w+)(\$|\%|\!|\#)?(?=\())</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\?|as(?=\s*#|\s*\w+\$)|auto|as|beep|bload|bsave|circle|clear|cload|close|cls|cmd|color|cont|copy|copy|csave|csrlin|data|(def)(dbl|(?=\s?fn)|int|sng|str|\s?usr)|delete|dim|draw|dsko\$|else|end|erase|error|field|files|for|get|gosub|goto|if|input|ipl|kanji|(?&lt;=:|^|\d)\s*key(?!\()|kill|let|line|list|llist|load|locate|lprint|lset|maxfiles|merge|motor|name|new|next|off|on|open|out|output|paint|play(?!(\()| +\()|point|poke|preset|print|pset|put|read|renum|restore|resume|return|rset|run|run|save|screen|(set)(\sadjust|\sbeep|\spage|\spassword|\sprompt|\sscreen|\sscroll|\stitle|\svideo|\b)|sound|sprite\$|sprite|step|stop|swap|then|to|troff|tron|using|vpoke|wait|width)</string>
					<key>name</key>
					<string>keyword.msx-basic-classic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:abs|asc|atn|attr\$|base|bin\$|cdbl|cdbl|chr\$|cint|cint|cos|csng|csng|cvd|cvi|cvs|date|dskf|eof|erl|err|exp|fix|fn|fpos|fre|hex\$|inkey\$|inp|input\$|instr|interval|int|key|left\$|len|loc|lof|log|lpos|mid\$|mkd\$|mki\$|mks\$|oct\$|pad|pdl|peek|play(?=(\(|\s+\())|pos|right\$|rnd|sgn|sin|space\$|spc|sqr|stick|str\$|strig|string\$|tab|tan|time|usr|val|varptr|varptr|vdp|vpeek)</string>
					<key>name</key>
					<string>support.function.msx-basic-classic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.msx-basic-classic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.msx-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(call\s+|_\s*)(\w{,15})</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>comment.msx-basic-classic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[.,;]</string>
					<key>name</key>
					<string>keyword.operator.msx-basic-classic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\+|-|\*|/|\^|\\|=|&lt;|&gt;|and|or|not|xor|eqv|imp|mod)</string>
					<key>name</key>
					<string>keyword.operator.msx-basic-classic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#?)([1-9]+[0-9]*|0)(\.?)([ed][+-])?([%!#]?)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.global.msx-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#?)([A-Za-z]\d*)([%!#\$]?)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-classic</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-classic</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;[hH])([0-9a-fA-F]+|)|(&amp;[bB])([01]+|)|(&amp;[oO])([1-7]+|)</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.msx-basic-classic</string>
</dict>
</plist>
