<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>name</key>
	<string>MSX Basic Dignified</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.msx-basic-dignified</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.msx-basic-dignified</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>comment.msx-basic-dignified</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.msx-basic-dignified</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Remtags</string>
					<key>match</key>
					<string>(?i)(^\s*##B(B|D):)(([a-zA-Z_0-9]+)(=)(.*$)|(msx\s*$))</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>comment</key>
					<string>Double quotes</string>
					<key>end</key>
					<string>"|$</string>
					<key>name</key>
					<string>string.quoted.double.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s*'')</string>
					<key>comment</key>
					<string>Regular comment block</string>
					<key>end</key>
					<string>(''\s*$)</string>
					<key>name</key>
					<string>comment.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s*###)</string>
					<key>comment</key>
					<string>Exclusive comment block</string>
					<key>end</key>
					<string>(###\s*$)</string>
					<key>name</key>
					<string>comment.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Exclusive comment inline</string>
					<key>match</key>
					<string>(^|\s*)##.*$</string>
					<key>name</key>
					<string>comment.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.msx-basic-dignified</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msx-basic-dignified</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>comment.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Regular comments</string>
					<key>match</key>
					<string>(?i)((')|(\brem\b))(.*)$</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*keep\s+</string>
					<key>comment</key>
					<string>Toggle rems keep</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>entity.name.tag.msx-basic-dignified</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(#[a-zA-Z_]\w*\s*)</string>
							<key>name</key>
							<string>entity.name.class.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.+</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Toggl rems line</string>
					<key>match</key>
					<string>^\s*#[a-zA-Z_]\w*\s+</string>
					<key>name</key>
					<string>entity.name.class.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=data)</string>
					<key>comment</key>
					<string>Data lines</string>
					<key>end</key>
					<string>(?=:)|$</string>
					<key>name</key>
					<string>constant.global.msx-basic-dignified</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>"</string>
							<key>end</key>
							<string>"|$</string>
							<key>name</key>
							<string>constant.global.msx-basic-dignified</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>[?] Define</string>
					<key>match</key>
					<string>\[\?\]</string>
					<key>name</key>
					<string>entity.name.class.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:^\s*define\s*)</string>
					<key>comment</key>
					<string>Define definitions</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>entity.name.tag.msx-basic-dignified</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\[\s*\]\s*(?=\[)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\[\W+\]\s*(?=\[)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\[[0-9_]+[A-Za-z_0-9]*\]\s*(?=\[)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\[[A-Za-z][A-Za-z_0-9]*\]\s*(?=\[)</string>
							<key>name</key>
							<string>entity.name.class.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[</string>
							<key>end</key>
							<string>\]|$</string>
							<key>name</key>
							<string>entity.name.class.msx-basic-dignified</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>\[</string>
									<key>end</key>
									<string>\]</string>
									<key>name</key>
									<string>entity.name.class.msx-basic-dignified</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\[</string>
											<key>name</key>
											<string>invalid.msx-basic-dignified</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#keywords</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#keywords</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>,\s*(,|(?=\n|\r))</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[^\[, \n\r]</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Define brackets</string>
					<key>match</key>
					<string>\[[A-Za-z][A-Za-z_0-9]*\]</string>
					<key>name</key>
					<string>entity.name.class.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\W)(_)(\s+($|(##.*$\n)))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.msx-basic-dignified</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Line join _</string>
					<key>end</key>
					<string>((?=_)|\n)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>^\s*\d+</string>
							<key>name</key>
							<string>constant.numeric.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Special cases for on xxx goto/gosub</string>
					<key>match</key>
					<string>\b(?i:error|interval|key|sprite|stop|strig)\s*(?=(?i:goto|gosub))\b</string>
					<key>name</key>
					<string>support.function.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msx-basic-dignified</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Special cases for defusr</string>
					<key>match</key>
					<string>\b(?i:def\s*usr(\d?))\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.function.msx-basic-dignified</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Special cases for usr</string>
					<key>match</key>
					<string>\b(?i:usr\s*(\d?)(?=\())\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.msx-basic-dignified</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.msx-basic-dignified</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Def fn</string>
					<key>match</key>
					<string>\b(?i:(fn)\s+(~?)(\w+)(\$|\%|\!|\#)?(?=\())</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Instructions</string>
					<key>match</key>
					<string>\b(?i:as(?=\s*#|\s*\w+\$)|auto|as|beep|bload|bsave|circle|clear|cload|close|cls|cmd|color|cont|copy|copy|csave|csrlin|data|(def)(dbl|(?=\s?fn)|int|sng|str)|delete|dim|draw|dsko\$|else|end|erase|error|field|files|for|get|gosub|goto|if|input(?!\$)|ipl|kanji|key(?!(\()| +\()|kill|let|line|list|llist|load|locate|lprint|lset|maxfiles|merge|motor|name|new|next|off|on|open|out|output|paint|play(?!(\()| +\()|point|poke|preset|print|pset|put|read|renum|restore|resume|return|rset|run|save|screen|(set)(\sadjust|\sbeep|\spage|\spassword|\sprompt|\sscreen|\sscroll|\stitle|\svideo|(\b|(?=_)))|sound|sprite\$|sprite|step|stop|swap|then|to|troff|tron|using|vpoke|wait|width)\b</string>
					<key>name</key>
					<string>keyword.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Functions without $</string>
					<key>match</key>
					<string>\b(?i:abs|asc|atn|base|cdbl|cdbl|cint|cint|cos|csng|csng|cvd|cvi|cvs|date|dskf|eof|erl|err|exp|fix|fn|fpos|fre|inp|instr|interval|int|key(?=(\(|\s+\())|len|loc|lof|log|lpos|pad|pdl|peek|play(?=(\(|\s+\())|pos|rnd|sgn|sin|spc|sqr|stick|strig|tab|tan|time|val|varptr|varptr|vdp|vpeek)\b</string>
					<key>name</key>
					<string>support.function.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.msx-basic-dignified</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Call and _ plus any 15 char string</string>
					<key>match</key>
					<string>\b(call\s+|_\s*)(\w{,15})\b</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Allows ? without the \b</string>
					<key>match</key>
					<string>[\?]</string>
					<key>name</key>
					<string>keyword.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Functions with $</string>
					<key>match</key>
					<string>\b(?i:attr\$|bin\$|chr\$|hex\$|inkey\$|input\$|left\$|mid\$|mkd\$|mki\$|mks\$|oct\$|right\$|space\$|str\$|string\$)</string>
					<key>name</key>
					<string>support.function.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Include</string>
					<key>match</key>
					<string>(?i:^\s*include)\b</string>
					<key>name</key>
					<string>entity.name.tag.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Endif</string>
					<key>match</key>
					<string>(?i:\bendif\b)</string>
					<key>name</key>
					<string>entity.name.tag.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Labels with only numbers</string>
					<key>match</key>
					<string>{\d+?}</string>
					<key>name</key>
					<string>invalid.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Labels with valid characters</string>
					<key>match</key>
					<string>{(\w+?|@)}</string>
					<key>name</key>
					<string>entity.name.class.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Labels with everything else</string>
					<key>match</key>
					<string>{.+?}</string>
					<key>name</key>
					<string>invalid.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Loop labels with only numbers</string>
					<key>match</key>
					<string>^\s*(\d+?){</string>
					<key>name</key>
					<string>invalid.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Loop labels open</string>
					<key>match</key>
					<string>^\s*(\w+?){\s*</string>
					<key>name</key>
					<string>entity.name.class.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Loop labels close</string>
					<key>match</key>
					<string>\s*}\s*$</string>
					<key>name</key>
					<string>entity.name.class.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Loop labels exit</string>
					<key>match</key>
					<string>\s*(?i:exit)\s*$</string>
					<key>name</key>
					<string>entity.name.tag.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Function definition</string>
					<key>match</key>
					<string>(?i:)(^\s*func\s+)</string>
					<key>name</key>
					<string>entity.name.tag.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Function call</string>
					<key>match</key>
					<string>(?i:)(\.\w+)(?=\()</string>
					<key>name</key>
					<string>entity.name.class.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Function ret</string>
					<key>match</key>
					<string>(?i:^\s*\bret\b)</string>
					<key>name</key>
					<string>entity.name.tag.cocobasicdignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Instruction separator</string>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>comment.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Separators</string>
					<key>match</key>
					<string>[.,;]</string>
					<key>name</key>
					<string>keyword.operator.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Operator signs and hash</string>
					<key>match</key>
					<string>(?i:\+|-|\*|/|\^|\\|=|&lt;&gt;|&gt;=|&lt;=|&lt;|&gt;|#)</string>
					<key>name</key>
					<string>keyword.operator.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Operator names</string>
					<key>match</key>
					<string>\b(?i:and|or|not|xor|eqv|imp|mod)\b</string>
					<key>name</key>
					<string>keyword.operator.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Booleans</string>
					<key>match</key>
					<string>\b(?i:true|false)\b</string>
					<key>name</key>
					<string>constant.numeric.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:)(^\s*declare(\s+|$))((,)|(?=.|\s))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.msx-basic-dignified</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Declare declarations</string>
					<key>end</key>
					<string>(?=$|##)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\s*)\w(\s*)(?=,|\n)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\s*(\w{1,2})(\:)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\W)\d+(\W)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.global.msx-basic-dignified</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.class.msx-basic-dignified</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.msx-basic-dignified</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*(\w{2,})((\:)[A-Za-z][A-Za-z0-9]?)?\s*(?=\n|,|##)</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[^,]+?(?=\n|,|##)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,\s*(?=\n|,|##)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Numbers starting a line</string>
					<key>match</key>
					<string>^\s*\d+</string>
					<key>name</key>
					<string>invalid.msx-basic-dignified</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-dignified</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Numbers</string>
					<key>match</key>
					<string>\b([0-9]+[0-9]*)(\.?)([ed][+-])?([%!#]?)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.msx-basic-dignified</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Variables</string>
					<key>match</key>
					<string>([A-Za-z]\d*)([%!#\$]?)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-dignified</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-dignified</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.msx-basic-dignified</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Hex, Octo and binary numbers</string>
					<key>match</key>
					<string>(&amp;[hH])([0-9a-fA-F]+)|(&amp;[bB])([01]+)|(&amp;[oO])([0-7]+)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(~)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.msx-basic-dignified</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>~ Variable definition</string>
					<key>end</key>
					<string>(\B|\W)</string>
					<key>name</key>
					<string>variable.other.msx-basic-dignified</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[A-Za-z_][A-Za-z_0-9]{2,}</string>
							<key>name</key>
							<string>variable.other.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\d+\w*(?=\W)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\w{0,2}(?=\W)</string>
							<key>name</key>
							<string>invalid.msx-basic-dignified</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.msx-basic-dignified</string>
</dict>
</plist>
