<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>name</key>
	<string>CoCo Basic classic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=DATA)</string>
					<key>end</key>
					<string>(?=:)|$</string>
					<key>name</key>
					<string>constant.global.coco-basic-classic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>keyword.operator.coco-basic-classic</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>"</string>
							<key>end</key>
							<string>"|$</string>
							<key>name</key>
							<string>constant.global.coco-basic-classic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"|$</string>
					<key>name</key>
					<string>string.quoted.double.coco-basic-classic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.coco-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.coco-basic-classic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>comment.coco-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((')|(REM))(.*)$</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(ASC)</string>
					<key>name</key>
					<string>support.function.coco-basic-classic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.coco-basic-classic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.coco-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.coco-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((FN)\s*(\w+)(\$)?(?=\())</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\?|AS(?=\S*#|\S*\W+\$)|AUDIO|BACKUP|CIRCLE|CLEAR|CLOAD|CLOADM|CLOSE|CLS|COLOR|CONT|COPY|CSAVE|CSAVEM|DATA|DEL|DIM|DIR|DLOAD|DRAW|DRIVE|DSKI\$|DSKINI|DSKO\$|EDIT|ELSE|END|EXEC|FIELD AS|FILES|FOR|GET|GOSUB|GOTO|IF|INPUT|KILL|LET|LINE|LIST|LLIST|LOAD|LOADM|LSET|MERGE|MOTOR|NEW|NEXT|OFF|ON|OPEN|PAINT|PCLEAR|PCLS|PCOPY|PLAY|PMODE|POKE|PRESET|PRINT(\S*TAB(?=\())?|PSET|PUT|READ|REM|RENAME|RENUM|RESET|RESTORE|RETURN|RSET|RUN|SAVE|SAVEM|SCREEN|SET|SKIPF|SOUND|STEP|STOP|THEN|TO|TROFF|TRON|UNLOAD|USING|VERIFY|WRITE)</string>
					<key>name</key>
					<string>keyword.coco-basic-classic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(ABS|ASC|ATN|COS|CVN|EOF|EXP|FIX|FREE|INSTR|INT|JOYSTK|LEN|LOC|LOF|LOG|MEM|PEEK|POINT|POS|PPOINT|RND|SGN|SIN|SQR|TAN|TIMER|USR|USRN|VAL|VARPTR|CHR\$|HEX\$|INKEY\$|LEFT\$|MID\$|MKN\$|RIGHT\$|STR\$|STRING\$)</string>
					<key>name</key>
					<string>support.function.coco-basic-classic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>comment.coco-basic-classic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=(PRINT)|\?)\s*@</string>
					<key>name</key>
					<string>keyword.coco-basic-classic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[.,;]</string>
					<key>name</key>
					<string>keyword.operator.coco-basic-classic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\+|-|\*|/|\^|\|=|&lt;|&gt;|AND|OR|NOT)</string>
					<key>name</key>
					<string>keyword.operator.coco-basic-classic</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.coco-basic-classic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.coco-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.coco-basic-classic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.coco-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#?)([1-9]+[0-9]*|0)(\.?)([E][+-])?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.coco-basic-classic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.global.coco-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.coco-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#?)([A-Z]\d*)([\$]?)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.coco-basic-classic</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.coco-basic-classic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.coco-basic-classic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.coco-basic-classic</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;[H])([0-9A-F]+|)|(&amp;[O])([1-7]+|)</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.coco-basic-classic</string>
</dict>
</plist>
